services:
  api:
    build: .
    container_name: findPostcode
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      MAX_BATCH_POSTCODES: ${MAX_BATCH_POSTCODES}
      DAILY_THROTTLE_RATE: ${DAILY_THROTTLE_RATE}
      PERMIN_THROTTLE_RATE: ${PERMIN_THROTTLE_RATE}
    healthcheck:
      test: [ "CMD", "python", "manage.py", "check" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
