services:
  api:
    build: .
    container_name: findPostcode
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      MAX_BATCH_POSTCODES: ${MAX_BATCH_POSTCODES}

