# Generated by Django 6.0.3 on 2026-03-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_postcode_area_postcode_district_postcode_easting_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcode',
            old_name='easting',
            new_name='eastings',
        ),
        migrations.RenameField(
            model_name='postcode',
            old_name='northing',
            new_name='northings',
        ),
    ]
