# Generated by Django 6.0.3 on 2026-03-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_easting_postcode_eastings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcode',
            name='area',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='district',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='eastings',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='northings',
            field=models.IntegerField(),
        ),
    ]
