# Generated by Django 6.0.3 on 2026-04-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_postcode_area_alter_postcode_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcode',
            name='date_introduced',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postcode',
            name='date_terminated',
            field=models.CharField(blank=True, null=True),
        ),
    ]
