# Generated by Django 6.0.3 on 2026-04-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_postcode_date_introduced_postcode_date_terminated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcode',
            name='eastings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postcode',
            name='northings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
