# Generated by Django 6.0.3 on 2026-04-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='findpostcodeuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='findpostcodeuser',
            name='comms_preferences',
        ),
        migrations.AlterField(
            model_name='findpostcodeuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='findpostcodeuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='ApiKeys',
        ),
    ]
